<?php

return [
    'Arica y Parinacota' => [
        'Arica' => [
            'Arica',
            'Camarones',
        ],
        'Parinacota' => [
            'Putre',
            'General Lagos',
        ],
    ],
    'Tarapacá' => [
        'Iquique' => [
            'Alto Hospicio',
            'Iquique',
        ],
        'Tamarugal' => [
            'Camiña',
            'Colchane',
            'Huara',
            'Pica',
            'Pozo Almonte',
        ],
    ],
    'Antofagasta' => [
        'Antofagasta' => [
            'Antofagasta',
            'Mejillones',
            'Sierra Gorda',
            'Taltal',
        ],
        'El Loa' => [
            'Calama',
            'Ollagüe',
            'San Pedro de Atacama',
        ],
        'Tocopilla' => [
            'Tocopilla',
            'María Elena',
        ],
    ],
    'Atacama' => [
        'Copiapó' => [
            'Copiapó',
            'Caldera',
            'Tierra Amarilla',
        ],
        'Chañaral' => [
            'Chañaral',
            'Diego de Almagro',
        ],
        'Huasco' => [
            'Vallenar',
            'Alto del Carmen',
            'Freirina',
            'Huasco',
        ],
    ],
    'Coquimbo' => [
        'Elqui' => [
            'Andacollo',
            'Coquimbo',
            'La Higuera',
            'La Serena',
            'Paihuano',
            'Vicuña',
        ],
        'Limarí' => [
            'Combarbalá',
            'Monte Patria',
            'Ovalle',
            'Punitaqui',
            'Río Hurtado',
        ],
        'Choapa' => [
            'Canela',
            'Illapel',
            'Los Vilos',
            'Salamanca',
        ],
    ],
    'Valparaíso' => [
        'Valparaíso' => [
            'Casablanca',
            'Concón',
            'Juan Fernández',
            'Puchuncaví',
            'Quintero',
            'Valparaíso',
            'Viña del Mar',
        ],
        'Marga Marga' => [
            'Limache',
            'Olmué',
            'Quilpué',
            'Villa Alemana',
        ],
        'Quillota' => [
            'Hijuelas',
            'La Calera',
            'La Cruz',
            'Nogales',
            'Quillota',
        ],
        'San Antonio' => [
            'Algarrobo',
            'Cartagena',
            'El Quisco',
            'El Tabo',
            'San Antonio',
        ],
        'Isla de Pascua' => [
            'Isla de Pascua',
        ],
        'Los Andes' => [
            'Calle Larga',
            'Los Andes',
            'Rinconada',
            'San Esteban',
        ],
        'San Felipe de Aconcagua' => [
            'Catemu',
            'Llaillay',
            'Panquehue',
            'Putaendo',
            'San Felipe',
            'Santa María',
        ],
        'Petorca' => [
            'Cabildo',
            'La Ligua',
            'Papudo',
            'Petorca',
            'Zapallar',
        ],
    ],
    'Metropolitana' => [
        'Santiago' => [
            'Cerrillos',
            'Cerro Navia',
            'Conchalí',
            'El Bosque',
            'Estación Central',
            'Huechuraba',
            'Independencia',
            'La Cisterna',
            'La Florida',
            'La Granja',
            'La Pintana',
            'La Reina',
            'Las Condes',
            'Lo Barnechea',
            'Lo Espejo',
            'Lo Prado',
            'Macul',
            'Maipú',
            'Ñuñoa',
            'Pedro Aguirre Cerda',
            'Peñalolén',
            'Providencia',
            'Pudahuel',
            'Quilicura',
            'Quinta Normal',
            'Recoleta',
            'Renca',
            'San Joaquín',
            'San Miguel',
            'San Ramón',
            'Santiago Centro',
            'Vitacura',
        ],
        'Chacabuco' => [
            'Colina',
            'Lampa',
            'Til Til',
        ],
        'Cordillera' => [
            'Pirque',
            'Puente Alto',
            'San José de Maipo',
        ],
        'Maipo' => [
            'Buin',
            'Calera de Tango',
            'Paine',
            'San Bernardo',
        ],
        'Melipilla' => [
            'Alhué',
            'Curacaví',
            'María Pinto',
            'Melipilla',
            'San Pedro',
        ],
        'Talagante' => [
            'El Monte',
            'Isla de Maipo',
            'Padre Hurtado',
            'Peñaflor',
            'Talagante',
        ],
    ],
    'O\'Higgins' => [
        'Cachapoal' => [
            'Codegua',
            'Coinco',
            'Coltauco',
            'Doñihue',
            'Graneros',
            'Las Cabras',
            'Machalí',
            'Malloa',
            'Mostazal',
            'Olivar',
            'Peumo',
            'Pichidegua',
            'Quinta de Tilcoco',
            'Rancagua',
            'Rengo',
            'Requínoa',
            'San Vicente',
        ],
        'Colchagua' => [
            'Chépica',
            'Chimbarongo',
            'Lolol',
            'Nancagua',
            'Palmilla',
            'Peralillo',
            'Placilla',
            'Pumanque',
            'San Fernando',
            'Santa Cruz',
        ],
        'Cardenal Caro' => [
            'La Estrella',
            'Litueche',
            'Marchigüe',
            'Navidad',
            'Paredones',
            'Pichilemu',
        ],
    ],
    'Maule' => [
        'Talca' => [
            'Constitución',
            'Curepto',
            'Empedrado',
            'Maule',
            'Pelarco',
            'Pencahue',
            'Río Claro',
            'San Clemente',
            'Talca',
        ],
        'Curicó' => [
            'Curicó',
            'Hualañé',
            'Licantén',
            'Molina',
            'Rauco',
            'Romeral',
            'Sagrada Familia',
            'Teno',
            'Vichuquén',
        ],
        'Linares' => [
            'Colbún',
            'Linares',
            'Longaví',
            'Parral',
            'Retiro',
            'San Javier',
            'Villa Alegre',
            'Yerbas Buenas',
        ],
        'Cauquenes' => [
            'Cauquenes',
            'Chanco',
            'Pelluhue',
        ],
    ],
    'Ñuble' => [
        'Diguillín' => [
            'Bulnes',
            'Chillán',
            'Chillán Viejo',
            'El Carmen',
            'Pemuco',
            'Pinto',
            'Quillón',
            'San Ignacio',
            'Yungay',
        ],
        'Itata' => [
            'Cobquecura',
            'Coelemu',
            'Ninhue',
            'Portezuelo',
            'Quirihue',
            'Ránquil',
            'Treguaco',
        ],
        'Punilla' => [
            'Coihueco',
            'Ñiquén',
            'San Carlos',
            'San Fabián',
            'San Nicolás',
        ],
    ],
    'Biobío' => [
        'Concepción' => [
            'Concepción',
            'Coronel',
            'Chiguayante',
            'Florida',
            'Hualqui',
            'Lota',
            'Penco',
            'San Pedro de la Paz',
            'Santa Juana',
            'Talcahuano',
            'Tomé',
            'Hualpén',
        ],
        'Biobío' => [
            'Alto Biobío',
            'Antuco',
            'Cabrero',
            'Laja',
            'Los Ángeles',
            'Mulchén',
            'Nacimiento',
            'Negrete',
            'Quilaco',
            'Quilleco',
            'San Rosendo',
            'Santa Bárbara',
            'Tucapel',
            'Yumbel',
        ],
        'Arauco' => [
            'Arauco',
            'Cañete',
            'Contulmo',
            'Curanilahue',
            'Lebu',
            'Los Álamos',
            'Tirúa',
        ],
    ],
    'La Araucanía' => [
        'Cautín' => [
            'Carahue',
            'Cholchol',
            'Cunco',
            'Curarrehue',
            'Freire',
            'Galvarino',
            'Gorbea',
            'Lautaro',
            'Loncoche',
            'Melipeuco',
            'Nueva Imperial',
            'Padre Las Casas',
            'Perquenco',
            'Pitrufquén',
            'Pucón',
            'Saavedra',
            'Temuco',
            'Teodoro Schmidt',
            'Toltén',
            'Vilcún',
            'Villarrica',
        ],
        'Malleco' => [
            'Angol',
            'Collipulli',
            'Curacautín',
            'Ercilla',
            'Lonquimay',
            'Los Sauces',
            'Lumaco',
            'Purén',
            'Renaico',
            'Traiguén',
            'Victoria',
        ],
    ],
    'Los Ríos' => [
        'Valdivia' => [
            'Corral',
            'Lanco',
            'Los Lagos',
            'Máfil',
            'Mariquina',
            'Paillaco',
            'Valdivia',
        ],
        'Ranco' => [
            'Futrono',
            'La Unión',
            'Lago Ranco',
            'Río Bueno',
        ],
    ],
    'Los Lagos' => [
        'Llanquihue' => [
            'Calbuco',
            'Cochamó',
            'Fresia',
            'Frutillar',
            'Llanquihue',
            'Maullín',
            'Puerto Montt',
            'Puerto Varas',
        ],
        'Osorno' => [
            'Osorno',
            'Puerto Octay',
            'Purranque',
            'Puyehue',
            'Río Negro',
            'San Juan de la Costa',
            'San Pablo',
        ],
        'Chiloé' => [
            'Ancud',
            'Castro',
            'Chonchi',
            'Curaco de Vélez',
            'Dalcahue',
            'Puqueldón',
            'Queilén',
            'Quellón',
            'Quinchao',
        ],
        'Palena' => [
            'Chaitén',
            'Futaleufú',
            'Hualaihué',
            'Palena',
        ],
    ],
    'Aysén' => [
        'Coyhaique' => [
            'Coyhaique',
            'Lago Verde',
        ],
        'Aysén' => [
            'Aysén',
            'Cisnes',
            'Guaitecas',
        ],
        'General Carrera' => [
            'Chile Chico',
            'Río Ibáñez',
        ],
        'Capitán Prat' => [
            'Cochrane',
            'O\'Higgins',
            'Tortel',
        ],
    ],
    'Magallanes y Antártica' => [
        'Magallanes' => [
            'Laguna Blanca',
            'Punta Arenas',
            'Río Verde',
            'San Gregorio',
        ],
        'Última Esperanza' => [
            'Natales',
            'Torres del Paine',
        ],
        'Tierra del Fuego' => [
            'Porvenir',
            'Primavera',
            'Timaukel',
        ],
        'Antártica Chilena' => [
            'Antártica',
            'Cabo de Hornos',
        ],
    ],
];
